# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
#     - name: Upload artifacts config-server
#       run : echo Uploading artifacts for config-server
#     - uses: actions/upload-artifact@v1
#       with:
#         name: Package
#         path: config-server/build/libs
#     - name: Upload artifacts currency-conversion-service
#       run : echo Uploading artifacts for currency-conversion-service
#     - uses: actions/upload-artifact@v1
#       with:
#         name: Package
#         path: currency-conversion-service/build/libs
#     - name: Upload artifacts currency-exchange-service
#       run : echo Uploading artifacts for currency-exchange-service
#     - uses: actions/upload-artifact@v1
#       with:
#         name: Package
#         path: currency-exchange-service/build/libs
#     - name: Upload artifacts eureka-naming-server
#       run : echo Uploading artifacts for eureka-naming-server
#     - uses: actions/upload-artifact@v1
#       with:
#         name: Package
#         path: eureka-naming-server/build/libs
#     - name: Upload artifacts limit-serv
#       run : echo Uploading artifacts for limit-serv
#     - uses: actions/upload-artifact@v1
#       with:
#         name: Package
#         path:  limit-serv/build/libs
#     - name: Upload artifacts zuul-api-gateway-service
#       run : echo Uploading artifacts for zuul-api-gateway-service
#     - uses: actions/upload-artifact@v1
#       with:
#         name: Package
#         path: zuul-api-gateway-service/build/libs
  

